org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel = true

# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=4.1.0
group=com.agricraft.agricraft
java_version=25

# Common
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# NeoForge https://neoforged.net/
neoforge_version=26.2.0.7-beta
neoforge_loader_version_range=[4,)

# Fabric https://fabricmc.net/develop/
fabric_version=0.153.0+26.2
fabric_loader_version=0.19.3

# Mod options
mod_name=AgriCraft
mod_author=InfinityRaider
mod_id=agricraft
license=MIT
credits=InfinityRaider, Ketheroth, coredex-source
description=Agricultural farming extended

# Mod deps
# https://modrinth.com/mod/modmenu/versions
modmenu_version=20.0.0-beta.4
rrv_version=7.1.4
# https://modrinth.com/mod/jei/versions
jei_version=30.1.0.12
# https://modrinth.com/mod/rei/versions
rei_version=26.2.820
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&showAlphaFiles=hide
jade_fabric_version=8285136
jade_forge_version=8281956
# https://modrinth.com/mod/wthit/versions
wthit_version=19.0.1
# https://modrinth.com/mod/eclipseui/versions
eclipseui_version=1.0.5+mc26.2-rc-2
eclipseui_fabric_version=EW0sBZm4
eclipseui_neoforge_version=qXA4HN0X
