org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel = true

# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=4.1.0
group=com.agricraft.agricraft
java_version=25

# Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1

# NeoForge https://neoforged.net/
neoforge_version=26.1.2.20-beta
neoforge_loader_version_range=[4,)

# Fabric https://fabricmc.net/develop/
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.19.2

# Mod options
mod_name=AgriCraft
mod_author=InfinityRaider
mod_id=agricraft
license=MIT
credits=InfinityRaider, Ketheroth, coredex-source
description=Agricultural farming extended

# Mod deps
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.8
rrv_version=7.1.4
# https://modrinth.com/mod/jei/versions
jei_version=29.5.0.26
# https://modrinth.com/mod/rei/versions
rei_version=21.11.814
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&showAlphaFiles=hide
jade_fabric_version=7886518
jade_forge_version=7938398
# https://modrinth.com/mod/wthit/versions
wthit_version=19.0.1
# https://modrinth.com/mod/eclipseui/versions
eclipseui_version=1.0.4+mc26.1
eclipseui_fabric_version=gh05XE4Y
eclipseui_neoforge_version=BnyvBfTX
