plugins {
	id 'multiloader-loader'
	id 'net.neoforged.moddev'
}

def commonProject = project(':common')

neoForge {
	version = neoforge_version
	// Automatically enable AccessTransformers if the file exists
	def at = commonProject.file('src/main/resources/META-INF/accesstransformer.cfg')
	if (at.exists()) {
		accessTransformers.from(at.absolutePath)
	}
	runs {
		configureEach {
			systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
			ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
		}
		client {
			client()
			gameDirectory = this.mkdir(this.file("runs/client"))
		}
		data {
			clientData()
			gameDirectory = this.mkdir(this.file("runs/data"))
			programArguments.addAll '--mod', project.mod_id, '--all',
					'--output', file('src/generated/resources/').getAbsolutePath(),
					'--existing', commonProject.file('src/main/resources/').getAbsolutePath(),
					'--existing', file('src/main/resources/').getAbsolutePath()
		}
		server {
			server()
			this.file("runs/server").createParentDirectories()
			gameDirectory = this.mkdir(this.file("runs/server"))
		}
	}
	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.processResources {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Jar).configureEach {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
sourceSets.main.java {
	// Exclude third-party mod compat plugins that don't have NeoForge builds yet
	exclude '**/plugin/industrialforegoing/**'
	exclude '**/plugin/pneumaticcraft/**'
	exclude '**/plugin/MysticalAgriculturePlugin.java'
}

dependencies {
	implementation "maven.modrinth:eclipseui:$eclipseui_neoforge_version"

	compileOnly "mezz.jei:jei-$minecraft_version-neoforge-api:$jei_version"
	runtimeOnly("mezz.jei:jei-$minecraft_version-neoforge:$jei_version") { transitive = false }

	compileOnly "mcp.mobius.waila:wthit-api:fabric-$wthit_version"

	implementation "curse.maven:jade-324717:$jade_forge_version"
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
	configurations.named("$variant") {
		attributes {
			attribute(loaderAttribute, 'neoforge')
		}
	}
}
sourceSets.configureEach {
	[it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
		configurations.named("$variant") {
			attributes {
				attribute(loaderAttribute, 'neoforge')
			}
		}
	}
}
